### ISSUE TITLE
请BOSS添加CI

### ISSUE THREAD

**Issue by uliian** [endink/Chopin#2]
请BOSS添加CI，然后将这玩意儿push到nuget上~我脚本都帮你写好了

**Comment by endink** [comment]
呃~我没有 Travis CI 账号呢，你没权限吗

**Comment by uliian** [comment]
主要我在纠结用哪个账号传nuget

**Comment by endink** [comment]
@uliian 把你 nuget 账号告诉我，我给你变成包的 owner 你就可以上传了啊，我已经传过一个版本了
